// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("otoroshi");

export declare const otoroshiAdminClientId: string | undefined;
Object.defineProperty(exports, "otoroshiAdminClientId", {
    get() {
        return __config.get("otoroshiAdminClientId");
    },
    enumerable: true,
});

export declare const otoroshiAdminClientSecret: string | undefined;
Object.defineProperty(exports, "otoroshiAdminClientSecret", {
    get() {
        return __config.get("otoroshiAdminClientSecret");
    },
    enumerable: true,
});

export declare const otoroshiAdminUrl: string | undefined;
Object.defineProperty(exports, "otoroshiAdminUrl", {
    get() {
        return __config.get("otoroshiAdminUrl");
    },
    enumerable: true,
});

