// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { DataExporterArgs } from "./dataExporter";
export type DataExporter = import("./dataExporter").DataExporter;
export const DataExporter: typeof import("./dataExporter").DataExporter = null as any;
utilities.lazyLoad(exports, ["DataExporter"], () => require("./dataExporter"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "otoroshi:events:DataExporter":
                return new DataExporter(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("otoroshi", "events", _module)
