// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace common {
    export interface LocationInputsArgs {
        teams?: pulumi.Input<pulumi.Input<string>[]>;
        tenant?: pulumi.Input<string>;
    }

}

export namespace proxy {
    export interface BackendInputsArgs {
        rewrite?: pulumi.Input<boolean>;
        root?: pulumi.Input<string>;
    }

    export interface FrontendInputsArgs {
        cookies?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        domains?: pulumi.Input<pulumi.Input<string>[]>;
        exact?: pulumi.Input<boolean>;
        headers?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        methods?: pulumi.Input<pulumi.Input<string>[]>;
        query?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        strip_path?: pulumi.Input<boolean>;
    }

}
