// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'otoroshi';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    declare public readonly otoroshiAdminClientId: pulumi.Output<string>;
    declare public readonly otoroshiAdminClientSecret: pulumi.Output<string>;
    declare public readonly otoroshiAdminUrl: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if (args?.otoroshiAdminClientId === undefined && !opts.urn) {
                throw new Error("Missing required property 'otoroshiAdminClientId'");
            }
            if (args?.otoroshiAdminClientSecret === undefined && !opts.urn) {
                throw new Error("Missing required property 'otoroshiAdminClientSecret'");
            }
            if (args?.otoroshiAdminUrl === undefined && !opts.urn) {
                throw new Error("Missing required property 'otoroshiAdminUrl'");
            }
            resourceInputs["otoroshiAdminClientId"] = args?.otoroshiAdminClientId ? pulumi.secret(args.otoroshiAdminClientId) : undefined;
            resourceInputs["otoroshiAdminClientSecret"] = args?.otoroshiAdminClientSecret ? pulumi.secret(args.otoroshiAdminClientSecret) : undefined;
            resourceInputs["otoroshiAdminUrl"] = args?.otoroshiAdminUrl;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["otoroshiAdminClientId", "otoroshiAdminClientSecret"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    otoroshiAdminClientId: pulumi.Input<string>;
    otoroshiAdminClientSecret: pulumi.Input<string>;
    otoroshiAdminUrl: pulumi.Input<string>;
}
